import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by peter on 20/01/15.
 */
public class ERScheduler {
    private JPanel panel1;
    private JTextField textField1;
    private JRadioButton fairConditionRadioButton;
    private JTextArea textArea1;
    private JRadioButton criticalConditionRadioButton;
    private JRadioButton seriousConditionRadioButton;
    private JButton scheduleButton;
    private JButton treatNextButton;
    private JButton treatAllButton;
    private QueueHandler qh;

    public ERScheduler() {
        // Support for 100 patients
        qh = new QueueHandler(100);
        scheduleButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                String name = textField1.getText();
                if (!name.equals("")) {
                    int prio = 0;
                    String echoCond = "Critical";
                    if (fairConditionRadioButton.isSelected()) {
                        prio = 2;
                        echoCond = "Fair";
                    } else if (seriousConditionRadioButton.isSelected()) {
                        prio = 1;
                        echoCond = "Serious";
                    }
                    Patient p = new Patient(name, prio);
                    qh.add(p);
                    textArea1.append(name + "\t" + echoCond + "\tWaiting...\n");
                    textField1.setText("");
                }
            }
        });
        treatNextButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                if (qh.getVirtSize() > 0) {
                    Patient temp = qh.remove();
                    textArea1.append(temp.getName() + " has been treated.\n");
                } else {
                    textArea1.append("No one to treat!\n");
                }
            }
        });
        treatAllButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                while (qh.getVirtSize() > 0) {
                    Patient temp = qh.remove();
                    textArea1.append(temp.getName() + " has been treated.\n");
                }
                textArea1.append("Everyone treated.\n");
            }
        });
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("ERScheduler");
        frame.setContentPane(new ERScheduler().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Patient Name");
        panel2.add(label1, BorderLayout.WEST);
        textField1 = new JTextField();
        textField1.setColumns(10);
        panel2.add(textField1, BorderLayout.EAST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.CENTER);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel3.add(panel4, BorderLayout.NORTH);
        fairConditionRadioButton = new JRadioButton();
        fairConditionRadioButton.setSelected(true);
        fairConditionRadioButton.setText("Fair Condition");
        panel4.add(fairConditionRadioButton, BorderLayout.WEST);
        scheduleButton = new JButton();
        scheduleButton.setText("Schedule");
        panel4.add(scheduleButton, BorderLayout.EAST);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel3.add(panel5, BorderLayout.SOUTH);
        criticalConditionRadioButton = new JRadioButton();
        criticalConditionRadioButton.setText("Critical Condition");
        panel5.add(criticalConditionRadioButton, BorderLayout.WEST);
        treatAllButton = new JButton();
        treatAllButton.setText("Treat All");
        panel5.add(treatAllButton, BorderLayout.EAST);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        panel3.add(panel6, BorderLayout.CENTER);
        seriousConditionRadioButton = new JRadioButton();
        seriousConditionRadioButton.setText("Serious Condition");
        panel6.add(seriousConditionRadioButton, BorderLayout.WEST);
        treatNextButton = new JButton();
        treatNextButton.setText("Treat Next");
        treatNextButton.setVerticalAlignment(0);
        panel6.add(treatNextButton, BorderLayout.EAST);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.SOUTH);
        textArea1 = new JTextArea();
        textArea1.setColumns(0);
        textArea1.setEditable(false);
        textArea1.setRows(10);
        scrollPane1.setViewportView(textArea1);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(fairConditionRadioButton);
        buttonGroup.add(seriousConditionRadioButton);
        buttonGroup.add(criticalConditionRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
